name: Build and Publish image to Docker Hub and Trigger Render Deployment
on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - 'frontend/**'

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Create Config.toml
              run: |
                cat > backend/Config.toml << 'EOF'
                [blog.backend]
                port = 9090

                [blog.backend.mongodb]
                connection_string = "${{ secrets.MONGODB_CONNECTION_STRING }}"
                database_name = "blogs"

                [blog.backend.asgardeo]
                issuer = "${{ secrets.ASGARDEO_ISSUER }}"
                audience = "${{ secrets.ASGARDEO_AUDIENCE }}"
                jwks_url = "${{ secrets.ASGARDEO_JWKS_URL }}"
                EOF
            - name: build image
              run: |
                 docker build ./backend/ -t puleena/blogy-be:latest
                 docker build ./frontend/ -t puleena/blogy-fe:latest
            - name: push image to docker hub
              run: |
                docker login -u puleena -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push puleena/blogy-be:latest
                docker push puleena/blogy-fe:latest

            # - name: Trigger Render Deployment
            #   run: |
            #     curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_API }}"